muban.海螺3.二级.content = '.hl-col-xs-12:eq(12)&&Text';
var rule = {
  模板: '海螺3',
  title: '短剧好看[短]',
  host: 'https://duanjuhk.cc',
  searchUrl: '/vodsearch/page/fypage/wd/**.html',
  url: '/vodshow/id/fyclassfyfilter.html',
  filterable: 1,
  filter: {
    "jingxuanduanju": [{ "key": "年份", "name": "年份", "value": [{ "n": "全部", "v": "" }, { "n": "2025", "v": "/year/2025" }, { "n": "2024", "v": "/year/2024" }, { "n": "2023", "v": "/year/2023" }, { "n": "2022", "v": "/year/2022" }, { "n": "2021", "v": "/year/2021" }, { "n": "2020", "v": "/year/2020" }, { "n": "2019", "v": "/year/2019" }, { "n": "2018", "v": "/year/2018" }, { "n": "2017", "v": "/year/2017" }, { "n": "2016", "v": "/year/2016" }, { "n": "2015", "v": "/year/2015" }, { "n": "2014", "v": "/year/2014" }, { "n": "2013", "v": "/year/2013" }, { "n": "2012", "v": "/year/2012" }, { "n": "2011", "v": "/year/2011" }, { "n": "2010", "v": "/year/2010" }] }, { "key": "字母", "name": "字母", "value": [{ "n": "全部", "v": "" }, { "n": "A", "v": "/letter/A" }, { "n": "B", "v": "/letter/B" }, { "n": "C", "v": "/letter/C" }, { "n": "D", "v": "/letter/D" }, { "n": "E", "v": "/letter/E" }, { "n": "F", "v": "/letter/F" }, { "n": "G", "v": "/letter/G" }, { "n": "H", "v": "/letter/H" }, { "n": "I", "v": "/letter/I" }, { "n": "J", "v": "/letter/J" }, { "n": "K", "v": "/letter/K" }, { "n": "L", "v": "/letter/L" }, { "n": "M", "v": "/letter/M" }, { "n": "N", "v": "/letter/N" }, { "n": "O", "v": "/letter/O" }, { "n": "P", "v": "/letter/P" }, { "n": "Q", "v": "/letter/Q" }, { "n": "R", "v": "/letter/R" }, { "n": "S", "v": "/letter/S" }, { "n": "T", "v": "/letter/T" }, { "n": "U", "v": "/letter/U" }, { "n": "V", "v": "/letter/V" }, { "n": "W", "v": "/letter/W" }, { "n": "X", "v": "/letter/X" }, { "n": "Y", "v": "/letter/Y" }, { "n": "Z", "v": "/letter/Z" }, { "n": "0-9", "v": "/letter/0-9" }] }, { "key": "by", "name": "排序", "value": [{ "n": "时间", "v": "/by/time" }, { "n": "人气", "v": "/by/hits" }, { "n": "评分", "v": "/by/score" }] }],
    "dushi": [{ "key": "字母", "name": "字母", "value": [{ "n": "全部", "v": "" }, { "n": "A", "v": "/letter/A" }, { "n": "B", "v": "/letter/B" }, { "n": "C", "v": "/letter/C" }, { "n": "D", "v": "/letter/D" }, { "n": "E", "v": "/letter/E" }, { "n": "F", "v": "/letter/F" }, { "n": "G", "v": "/letter/G" }, { "n": "H", "v": "/letter/H" }, { "n": "I", "v": "/letter/I" }, { "n": "J", "v": "/letter/J" }, { "n": "K", "v": "/letter/K" }, { "n": "L", "v": "/letter/L" }, { "n": "M", "v": "/letter/M" }, { "n": "N", "v": "/letter/N" }, { "n": "O", "v": "/letter/O" }, { "n": "P", "v": "/letter/P" }, { "n": "Q", "v": "/letter/Q" }, { "n": "R", "v": "/letter/R" }, { "n": "S", "v": "/letter/S" }, { "n": "T", "v": "/letter/T" }, { "n": "U", "v": "/letter/U" }, { "n": "V", "v": "/letter/V" }, { "n": "W", "v": "/letter/W" }, { "n": "X", "v": "/letter/X" }, { "n": "Y", "v": "/letter/Y" }, { "n": "Z", "v": "/letter/Z" }, { "n": "0-9", "v": "/letter/0-9" }] }, { "key": "by", "name": "排序", "value": [{ "n": "时间", "v": "/by/time" }, { "n": "人气", "v": "/by/hits" }, { "n": "评分", "v": "/by/score" }] }],
    "chuanyue": [{ "key": "年份", "name": "年份", "value": [{ "n": "全部", "v": "" }, { "n": "2025", "v": "/year/2025" }, { "n": "2024", "v": "/year/2024" }, { "n": "2023", "v": "/year/2023" }, { "n": "2022", "v": "/year/2022" }, { "n": "2021", "v": "/year/2021" }, { "n": "2020", "v": "/year/2020" }, { "n": "2019", "v": "/year/2019" }, { "n": "2018", "v": "/year/2018" }, { "n": "2017", "v": "/year/2017" }, { "n": "2016", "v": "/year/2016" }, { "n": "2015", "v": "/year/2015" }, { "n": "2014", "v": "/year/2014" }, { "n": "2013", "v": "/year/2013" }, { "n": "2012", "v": "/year/2012" }, { "n": "2011", "v": "/year/2011" }, { "n": "2010", "v": "/year/2010" }] }, { "key": "字母", "name": "字母", "value": [{ "n": "全部", "v": "" }, { "n": "A", "v": "/letter/A" }, { "n": "B", "v": "/letter/B" }, { "n": "C", "v": "/letter/C" }, { "n": "D", "v": "/letter/D" }, { "n": "E", "v": "/letter/E" }, { "n": "F", "v": "/letter/F" }, { "n": "G", "v": "/letter/G" }, { "n": "H", "v": "/letter/H" }, { "n": "I", "v": "/letter/I" }, { "n": "J", "v": "/letter/J" }, { "n": "K", "v": "/letter/K" }, { "n": "L", "v": "/letter/L" }, { "n": "M", "v": "/letter/M" }, { "n": "N", "v": "/letter/N" }, { "n": "O", "v": "/letter/O" }, { "n": "P", "v": "/letter/P" }, { "n": "Q", "v": "/letter/Q" }, { "n": "R", "v": "/letter/R" }, { "n": "S", "v": "/letter/S" }, { "n": "T", "v": "/letter/T" }, { "n": "U", "v": "/letter/U" }, { "n": "V", "v": "/letter/V" }, { "n": "W", "v": "/letter/W" }, { "n": "X", "v": "/letter/X" }, { "n": "Y", "v": "/letter/Y" }, { "n": "Z", "v": "/letter/Z" }, { "n": "0-9", "v": "/letter/0-9" }] }, { "key": "by", "name": "排序", "value": [{ "n": "时间", "v": "/by/time" }, { "n": "人气", "v": "/by/hits" }, { "n": "评分", "v": "/by/score" }] }],
    "gudai": [{ "key": "年份", "name": "年份", "value": [{ "n": "全部", "v": "" }, { "n": "2025", "v": "/year/2025" }, { "n": "2024", "v": "/year/2024" }, { "n": "2023", "v": "/year/2023" }, { "n": "2022", "v": "/year/2022" }, { "n": "2021", "v": "/year/2021" }, { "n": "2020", "v": "/year/2020" }, { "n": "2019", "v": "/year/2019" }, { "n": "2018", "v": "/year/2018" }, { "n": "2017", "v": "/year/2017" }, { "n": "2016", "v": "/year/2016" }, { "n": "2015", "v": "/year/2015" }, { "n": "2014", "v": "/year/2014" }, { "n": "2013", "v": "/year/2013" }, { "n": "2012", "v": "/year/2012" }, { "n": "2011", "v": "/year/2011" }, { "n": "2010", "v": "/year/2010" }] }, { "key": "字母", "name": "字母", "value": [{ "n": "全部", "v": "" }, { "n": "A", "v": "/letter/A" }, { "n": "B", "v": "/letter/B" }, { "n": "C", "v": "/letter/C" }, { "n": "D", "v": "/letter/D" }, { "n": "E", "v": "/letter/E" }, { "n": "F", "v": "/letter/F" }, { "n": "G", "v": "/letter/G" }, { "n": "H", "v": "/letter/H" }, { "n": "I", "v": "/letter/I" }, { "n": "J", "v": "/letter/J" }, { "n": "K", "v": "/letter/K" }, { "n": "L", "v": "/letter/L" }, { "n": "M", "v": "/letter/M" }, { "n": "N", "v": "/letter/N" }, { "n": "O", "v": "/letter/O" }, { "n": "P", "v": "/letter/P" }, { "n": "Q", "v": "/letter/Q" }, { "n": "R", "v": "/letter/R" }, { "n": "S", "v": "/letter/S" }, { "n": "T", "v": "/letter/T" }, { "n": "U", "v": "/letter/U" }, { "n": "V", "v": "/letter/V" }, { "n": "W", "v": "/letter/W" }, { "n": "X", "v": "/letter/X" }, { "n": "Y", "v": "/letter/Y" }, { "n": "Z", "v": "/letter/Z" }, { "n": "0-9", "v": "/letter/0-9" }] }, { "key": "by", "name": "排序", "value": [{ "n": "时间", "v": "/by/time" }, { "n": "人气", "v": "/by/hits" }, { "n": "评分", "v": "/by/score" }] }],
    "fuliduanju": [{ "key": "类型", "name": "类型", "value": [{ "n": "全部", "v": "" }, { "n": "日本伦理", "v": "/class/日本伦理" }, { "n": "韩国伦理", "v": "/class/韩国伦理" }, { "n": "港台三级", "v": "/class/港台三级" }, { "n": "西方伦理", "v": "/class/西方伦理" }, { "n": "里番动漫", "v": "/class/里番动漫" }] }, { "key": "年份", "name": "年份", "value": [{ "n": "全部", "v": "" }, { "n": "2025", "v": "/year/2025" }, { "n": "2024", "v": "/year/2024" }, { "n": "2023", "v": "/year/2023" }, { "n": "2022", "v": "/year/2022" }, { "n": "2021", "v": "/year/2021" }, { "n": "2020", "v": "/year/2020" }, { "n": "2019", "v": "/year/2019" }, { "n": "2018", "v": "/year/2018" }, { "n": "2017", "v": "/year/2017" }, { "n": "2016", "v": "/year/2016" }, { "n": "2015", "v": "/year/2015" }, { "n": "2014", "v": "/year/2014" }, { "n": "2013", "v": "/year/2013" }, { "n": "2012", "v": "/year/2012" }, { "n": "2011", "v": "/year/2011" }, { "n": "2010", "v": "/year/2010" }] }, { "key": "字母", "name": "字母", "value": [{ "n": "全部", "v": "" }, { "n": "A", "v": "/letter/A" }, { "n": "B", "v": "/letter/B" }, { "n": "C", "v": "/letter/C" }, { "n": "D", "v": "/letter/D" }, { "n": "E", "v": "/letter/E" }, { "n": "F", "v": "/letter/F" }, { "n": "G", "v": "/letter/G" }, { "n": "H", "v": "/letter/H" }, { "n": "I", "v": "/letter/I" }, { "n": "J", "v": "/letter/J" }, { "n": "K", "v": "/letter/K" }, { "n": "L", "v": "/letter/L" }, { "n": "M", "v": "/letter/M" }, { "n": "N", "v": "/letter/N" }, { "n": "O", "v": "/letter/O" }, { "n": "P", "v": "/letter/P" }, { "n": "Q", "v": "/letter/Q" }, { "n": "R", "v": "/letter/R" }, { "n": "S", "v": "/letter/S" }, { "n": "T", "v": "/letter/T" }, { "n": "U", "v": "/letter/U" }, { "n": "V", "v": "/letter/V" }, { "n": "W", "v": "/letter/W" }, { "n": "X", "v": "/letter/X" }, { "n": "Y", "v": "/letter/Y" }, { "n": "Z", "v": "/letter/Z" }, { "n": "0-9", "v": "/letter/0-9" }] }, { "key": "by", "name": "排序", "value": [{ "n": "时间", "v": "/by/time" }, { "n": "人气", "v": "/by/hits" }, { "n": "评分", "v": "/by/score" }] }]
  },
  filter_url: '{{fl.排序}}{{fl.类型}}{{fl.字母}}/page/fypage{{fl.年份}}',
  cate_exclude: '明星|专题|最新|排行|福利短剧',
}