var rule = {
  title: '樱花视频',
  host: 'https://yinghuadm.fun',
  url: '/vodshow/fyfilter.html',
  searchUrl: '/vodsearch/**----------fypage---.html',
  searchable: 2,
  quickSearch: 1,
  filterable: 1,
  filter_url: '{{fl.类型}}-{{fl.地区}}-{{fl.排序}}-{{fl.剧情}}-{{fl.语言}}-{{fl.字母}}---fypage---{{fl.年份}}',
  filter_def: { 1: { 类型: "1" }, 2: { 类型: "2" }, 3: { 类型: "3" }, 4: { 类型: "4" }, },
  filter: 'H4sIAAAAAAAAA+2Za08bVxCG/4s/U2kXaJLmW+73+z1VPkQVUqO2qdSklaoICTAmhoANiOBQzK3hForBXErBruHP+Oza/yJrn5l3xlJZWS1q1Xa/+Xlnz9kzc3aWl7OvYm7s5OevYl91/Bg7GTP9S148EWuJPX/6TYfmH55+/X1H/cLnNTmxXI0v1+QAYp0tpI5ng+tJJeCYn9ygiQQ45nUPe13jFCPAnAPL5VKW57SAOZdGzF6R57SAcVi4AO6XfFcu9PP9LHCskls0gysUI8D9Btb9EscI1Dr9saKsswaILbyWdRJgLbnF8v4sr8UCxvWNVic+8DgLGDe9Eqycx1lopp5ez6o/PsIxC4jFB7yenzhmAbkX0yaxy7lb4Fh1atR7t0AxAsw5/rrSX+A5LSC//TV/7FdT2uAUwbgiPV95j120gFiqz6Q3OWYBu3gwHOwB76IFqWrWmxpBVeuAWO+B/wtnQoAKlEb8YrZhwQ1S55PaldRG2bwZLKg2Ym6qjeaXqhN9vAgLKPXihLe7zqW2IMXKe3v7KFYdsPj9lJks8bItYIu23kqMAIV8syExAozLLHjZVR5nAeuc+SDjCGTbf5MYgawlr9eSbxg3lDeFRR5nAeN600GlTJK7RRiZLBz46ZzfP8HJgKWFZ703B8EwdDEzrkjslIvcWAQN2763XS6W1LYzN7PtrU7rp6TVfyq9XfR2rbeJ3qb1VtFbte6K7mrdEd1RuvsZ9OCn0k+IfkLrx0U/rvVjoh/TuuTr6nxdydfV+bqSr6vzdSVfV+frSr6uzteVfF2dryP5OjpfR/J1dL6O5OXovBzJy9F5OZJX8FM/OJX1XGW5Sx4ccFPvi8lScD0/lRZU/0qMAO+EzXmJEaB/MyUzlJGwsOpwFbag3gwSI1BvGxWzoN4MKhMLqvfMWlx6rwYNvZfLeOtDqveYmynhKRJOQTlNymkoZ0g5A+UsKWehnCPlHJTzpJyHcoGUC1AuknIRyiVSLkG5TMplKFdIuQLlKilXoVwj5RqU66Rch3KDlBtQbpJyE8otUm5BuU3KbSh3SLkD5S4pd6HcI+UelPuk3IfygJQHUB6S8hDKI1IeQXlMymMozifczrVf+lHxUqOmkJZHBdz4qHiZnWpmm+Z4+Sy4lKcuFwpefowiXz57+UL6bb3XJPlv94svvv2uo3bnJy2x1iMz2SGWKMzYWl9mundMPN1g1UhqxsSbtR1TQH9aaNIcH2riw8xxmIkPs39hZrW8Nyf2j0AMcMKbYHdFgPu97RPDTaCsodSMoGnP8JesYl8iuB5etg7NWLA/ayPDLF+4xTzc1oVazPF84MLM1Bz+gWCOLFlkySJLdjSWLLJWkbX6F1urtqOyVtWufn+pi/vHgrYGvTPKGgSAla0dVPJJ7mgLGDea8wb4RIlAejLh7bJNIZBe3irvDaOX66D+0lbf81oIECusmLVpjlnA/SY31VmcBYwbm/G2cZZqAeN2d71kulwYlTO1Bgl12P45MFtcBwuYY6On0j3Ioy38LTYosDaBicGy66BeisFrUl6KNUBsdSkoLccsRMYiMhaRsYiMRSwyFv8HY9F+VMYizDyEfcT047nKHBsSAsyZWvaHedUEiA1P+6v4yGdB/lYe/lGxMjxVSfH5EQHmnJ0zk+hzC5gz5HzHyxbUh0oLuF/IZ7qwsyyTD8rEu0ygYwtbKhYA6jm/X/6dP3ASYFxqxiQneZwFeXY2TY7NGAHmnBzwJthUEUhdNsxBBnWpg3o3/jPnQmFnOH9oeppdcGSIIkMUGaLIEEWG6L9piDo/AsLyrmsrJgAA',
  headers: { 'User-Agent': 'UC_UA' },
  timeout: 5000,
  class_name: '电影&剧集&综艺&动漫',
  class_url: '1&2&3&4',
  play_parse: true,
  limit: 6,
  double:true,
  推荐:'*',
  一级:'.fed-list-item.fed-padding;.fed-list-title.fed-font-xiv&&Text;a&&data-original;.fed-text-white.fed-text-center&&Text;a&&href',
  二级:{
    title:'h1&&Text;.fed-col-md3.fed-part-eone:eq(0)&&Text',
    img:'a&&data-original',
    desc:'.fed-col-md6.fed-part-eone:eq(2)&&Text;.fed-col-md3.fed-part-eone:eq(2)&&Text;.fed-col-md3.fed-part-eone:eq(1)&&Text;.fed-col-md6.fed-part-eone:eq(0)&&Text;.fed-col-md6.fed-part-eone:eq(1)&&Text',
    content:'.fed-part-esan&&Text',
    tabs:'.fed-drop-btns.fed-padding',
    lists:'.fed-play-item.fed-drop-item:eq(#id)&&a:gt(0)',
    tab_text:'body&&Text',
    list_text:'body&&Text',
    list_url:'a&&href',
    list_url_prefix: '',
  },
  搜索:'.fed-deta-info.fed-deta-padding;h1&&Text;a&&data-original;.fed-col-xs6.fed-col-md3&&Text;a&&href;.video-info-aux&&Text',
}