var rule = {
  title: '皮皮虾[优]',
  host: 'https://ppxys.cc',
  class_name: '电影&电视剧&综艺&动漫',
  class_url: '1&2&3&4',
  searchUrl: '/index.php/ajax/suggest?mid=1&wd=**&limit=50',
  searchable: 2,
  quickSearch: 0,
  headers: {
    'User-Agent': 'MOBILE_UA',
  },
  url: '/index.php/vod/type/id/fyclass.html',
  filterable: 0,
  filter_url: '',
  filter: {},
  filter_def: {},
  detailUrl: '/index.php/vod/detail/id/fyid.html',
  play_parse: true,
  lazy: "js:\n  let html = request(input);\n  let hconf = html.match(/r player_.*?=(.*?)</)[1];\n  let json = JSON5.parse(hconf);\n  let url = json.url;\n  if (json.encrypt == '1') {\n    url = unescape(url);\n  } else if (json.encrypt == '2') {\n    url = unescape(base64Decode(url));\n  }\n  if (/\\.(m3u8|mp4|m4a|mp3)/.test(url)) {\n    input = {\n      parse: 0,\n      jx: 0,\n      url: url,\n    };\n  } else {\n    input;\n  }",
  limit: 6,
  推荐: '.slide-time-bj;h3&&Text;.slide-time-img3&&style;.slide-info-remarks:eq(1)&&Text;a&&href;.slide-info:eq(3)&&Text',
  一级:'.public-list-box.public-pic-b;a&&title;img&&data-src;.public-list-prb.hide&&Text;a&&href',
  二级: {
    title: '.slide-info-title&&Text;.slide-info:eq(2)--strong&&Text',
    img: '.lazy&&data-src',
    desc: '.slide-info-remarks&&Text;.slide-info-remarks:eq(1)&&Text;.slide-info-remarks:eq(2)&&Text;.slide-info:eq(1)--strong&&Text;.info-parameter&&ul&&li:eq(3)&&Text',
    content: '#height_limit&&Text',
    tabs: '.anthology.wow.fadeInUp.animated&&.swiper-wrapper&&a',
    tab_text: 'a--span&&Text',
    lists: '.anthology-list-box:eq(#id) li',
  },
  搜索: 'json:list;name;pic;;id',
}