var rule = {
    title: '红狐影视',
    host: 'https://video.mrgaocloud.com',
    url: '/index.php/vod/show/id/fyclass/page/fypage.html',
    searchUrl: '/index.php/vod/search/page/fypage/wd/**.html',
    searchable: 2,
    quickSearch: 0,
    headers: {
        'User-Agent': 'MOBILE_UA',
    },
    timeout: 5000,
    class_name:'电影&电视剧&动漫&B站&综艺&纪录片',
    class_url:'1&2&3&28&4&34', 
    cate_exclude: '',
    play_parse: true,
    lazy:muban.mx.lazy,
    double: true,
    推荐: '*',
    一级: 'body&&.list-width;a&&title;.eclazy&&data-original;.list-remarks&&Text;a&&href;.detail&&Text',
    二级: {
        title: '.detail-a .hidden&&Text;h2&&Text',
        img: '.eclazy&&data-original',
        desc: '.detail-a li:eq(1)--span&&Text;.detail-a .vodTag&&a&&Text;.detail-a .vodTag&&a:eq(1)&&Text;.detail-a li:eq(2)--span&&Text;.detail-a li:eq(3)--span&&Text',
        content: '.ecshow--span--i--i&&Text',
        tabs: '.play_source_tab a--em',
        lists: '.playlist_notfull:eq(#id) li',
    },
    搜索: '*',
}