var rule = {
  类型:'影视',//影视|听书|漫画|小说
  title:'狐狸君[磁]',
  host:'https://www.foxjun.com',
  url:'/channel/fyclass.html?apage1=fypage',
  searchUrl:'/s?q=**&orderway=desc&page=fypage',
  searchable:2,
  quickSearch:0,
  filterable:0,
  headers:{
	  'User-Agent':'MOBILE_UA',
  },
  timeout:5000,
  class_parse:'.navbar-nav li;a&&Text;a&&href;.*/(.*?)\.html',
  cate_exclude:'',
  play_parse:true,
  lazy:'',
  double:true,
  推荐:'.col-xs-12 li;li;.img-zoom&&title;img&&src;;a&&href',
  一级:'body .col-xs-6;.media-left span&&title;img&&src;;a&&href',
  二级:{
	title:'.col-xs-12 a:eq(2)&&Text;.col-xs-12 p:eq(3)&&Text',
	img:'.movie-poster img&&src',
	desc:'.col-xs-12 p:eq(5)&&Text;.col-xs-12 p:eq(4)&&Text;地区;.movie-scroller&&Text;导演',
	content:'.col-xs-12 p:eq(7)&&title',
	tabs:'.tab-content td:gt(0)',
	lists:'.tab-pane:eq(#id)&&a:gt(0)',
	tab_text:'body&&Text',
	list_text:'body&&Text',
	list_url:'a&&href',
	list_url_prefix: '',
  },
  搜索:'.article-item;img&&alt;*;.tag-primary&&Text;*;.article-tag span&&Text',
}